version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Welcome01}
      PGDATA: /data/postgres
    
    volumes:
      - postgres:/data/postgres
    
    ports:
      - "5432:5432"

    
    networks: 
      - postgres
      
    
    restart: unless-stopped

  